title = "Techree"
baseURL = "https://www.techree.net/"
languageCode = "en-us"
theme = "ananke"
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-43834958-5"
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  title = "Techree"
  description = "iOSエンジニアが日頃の技術的なことをメモするブログです"
  images = ["/images/ogp-image.jpg"]
  favicon = ""
  facebook = ""
  twitter = "https://twitter.com/nagami_hiro"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/header-img.jpg"
  recent_posts_number = 2
